imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true

  # Controller
  Oksydan\IsProductExtraTabs\Controller\ProductExtraTabController:
    public: true
    class: Oksydan\IsProductExtraTabs\Controller\ProductExtraTabController
    arguments:
      - "@=service('prestashop.adapter.legacy.context').getLanguages(false)"

  # installer
  oksydan.is_product_extra_tab.product_extra_tab_installer:
    class: 'Oksydan\IsProductExtraTabs\Installer\ProductExtraTabInstaller'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '@oksydan.is_product_extra_tab.installer.database_yml_parser'
      - "@=service('prestashop.adapter.legacy.context').getContext()"

  oksydan.is_product_extra_tab.installer.database_yml_parser:
    class: 'Oksydan\IsProductExtraTabs\Installer\DatabaseYamlParser'
    arguments:
      - '@oksydan.is_product_extra_tab.installer.database_yml_parser_provider'

  oksydan.is_product_extra_tab.installer.database_yml_parser_provider:
    class: 'Oksydan\IsProductExtraTabs\Installer\Provider\DatabaseYamlProvider'
    arguments:
      - '@oksydan.is_product_extra_tab.module'

  oksydan.is_product_extra_tab.installer.action_database_create_table:
    class: 'Oksydan\IsProductExtraTabs\Installer\ActionDatabaseCrateTable'
    parent: 'oksydan.is_product_extra_tab.installer.abstract_action_database'
    public: true

  oksydan.is_product_extra_tab.installer.action_database_drop_table:
    class: 'Oksydan\IsProductExtraTabs\Installer\ActionDatabaseDropTable'
    parent: 'oksydan.is_product_extra_tab.installer.abstract_action_database'
    public: true

  oksydan.is_product_extra_tab.installer.abstract_action_database:
    class: 'Oksydan\IsProductExtraTabs\Installer\ActionDatabaseAbstract'
    abstract: true
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  #creation/edition form
  oksydan.is_product_extra_tab.form.identifiable_object.data_provider.product_extra_tab_form_data_provider:
    class: 'Oksydan\IsProductExtraTabs\Form\Provider\ProductExtraTabFormDataProvider'
    arguments:
      - '@oksydan.is_product_extra_tab.repository.product_extra_tab'
      - '@prestashop.adapter.shop.context'

  oksydan.is_product_extra_tab.form.identifiable_object.builder.product_extra_tab_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Oksydan\IsProductExtraTabs\Form\ProductExtraTabType'
      - '@oksydan.is_product_extra_tab.form.identifiable_object.data_provider.product_extra_tab_form_data_provider'

  oksydan.is_product_extra_tab.form.identifiable_object.data_handler.product_extra_tab_form_data_handler:
    class: 'Oksydan\IsProductExtraTabs\Form\DataHandler\ProductExtraTabFormDataHandler'
    arguments:
      - '@oksydan.is_product_extra_tab.repository.product_extra_tab'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"

  oksydan.is_product_extra_tab.form.identifiable_object.handler.product_extra_tab_form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@oksydan.is_product_extra_tab.form.identifiable_object.data_handler.product_extra_tab_form_data_handler'

  #grid services
  oksydan.is_product_extra_tab.grid.definition.factory.product_extra_tab:
    class: 'Oksydan\IsProductExtraTabs\Grid\Definition\Factory\ProductExtraTabGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  oksydan.is_product_extra_tab.grid.query.product_extra_tab_query_builder:
    class: 'Oksydan\IsProductExtraTabs\Grid\Query\ProductExtraTabQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.adapter.shop.context'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"

  oksydan.is_product_extra_tab.grid.product_extra_tab_grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@oksydan.is_product_extra_tab.grid.definition.factory.product_extra_tab'
      - '@oksydan.is_product_extra_tab.grid.data.factory.product_extra_tab_decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'


  oksydan.is_product_extra_tab.grid.data.factory.product_extra_tab_data_factory:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@oksydan.is_product_extra_tab.grid.query.product_extra_tab_query_builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'is_product_extra_tab'


  oksydan.is_product_extra_tab.grid.data.factory.product_extra_tab_decorator:
    class: 'Oksydan\IsProductExtraTabs\Grid\Data\Factory\ProductExtraTabGridDataFactory'
    arguments:
      - '@oksydan.is_product_extra_tab.grid.data.factory.product_extra_tab_data_factory'

  oksydan.is_product_extra_tab.form.product_extra_tab_type:
    class: 'Oksydan\IsProductExtraTabs\Form\ProductExtraTabType'
    parent: 'form.type.translatable.aware'
    arguments:
      - '@=service("prestashop.adapter.multistore_feature").isUsed()'
    public: true
    tags:
      - { name: form.type }

# Admin product Hook
  oksydan.is_product_extra_tab.form.identifiable_object.data_provider.product_extra_tab_product_form_data_provider:
    class: 'Oksydan\IsProductExtraTabs\Form\Provider\ProductExtraTabProductFormDataProvider'
    arguments:
      - '@oksydan.is_product_extra_tab.repository.product_extra_tab'
      - '@oksydan.is_product_extra_tab.repository.product_extra_tab_product'
      - '@prestashop.adapter.shop.context'

  oksydan.is_product_extra_tab.form.product_extra_tab_product_type:
    class: 'Oksydan\IsProductExtraTabs\Form\ProductExtraTabProductType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  oksydan.is_product_extra_tab.form.identifiable_object.data_handler.product_extra_tab_product_form_data_handler:
    class: 'Oksydan\IsProductExtraTabs\Form\DataHandler\ProductExtraTabProductFormDataHandler'
    arguments:
      - '@oksydan.is_product_extra_tab.repository.product_extra_tab'
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'
      - "@=service('prestashop.adapter.legacy.context').getLanguages()"

  oksydan.is_product_extra_tab.grid.position_definition:
    class: PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition
    arguments:
      - 'product_extra_tab'
      - 'id_product_extra_tab'
      - 'position'

  oksydan.is_product_extra_tab.hook.display_admin_products_extra:
    class: Oksydan\IsProductExtraTabs\Hook\DisplayAdminProductsExtra
    parent: 'oksydan.is_product_extra_tab.hook.abstract_display_hook'
    public: true
